version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - apt-get install -y unzip

  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
   
artifacts:
  type: 
  files:
   - '**/*'
